name = "JuliaSub"
uuid = "7a8e1ac7-1981-4f50-b715-6a5b66e1820b"
authors = ["Julia Belyakova <julbinb@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Multisets = "3b2b4ff1-bcff-5658-a3ee-dbcf1ce5ac09"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
